version: '3'

services:
  wordpress:
    volumes:
      - ./datavolume:/var/www/html/wp-content
      - .uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root